appearance:
  default: light
  switcher: true
  colors:
    primary:
      light: "#0f766e"
      dark: "#2dd4bf"
    accent:
      light: "#be123c"
      dark: "#fb7185"
    positive:
      light: "#15803d"
      dark: "#4ade80"
    warning:
      light: "#b45309"
      dark: "#fbbf24"
deployment:
  basePath: /femi
plugins:
  components:
    "@evidence-dev/core-components": {}
  datasources:
    "@evidence-dev/postgres": {}
